# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'zingimmick'

branding:
    icon: 'check'
    color: 'blue'

description: 'Use Easy Coding Standard via GithubAction.'

name: 'ecs-action'

runs:
    using: 'docker'
    image: 'Dockerfile'
